### ISSUE TITLE
Warning: Cannot modify header information - headers already sent by 

### ISSUE THREAD

**Issue by 11mb** [Magento2Translations/language_nl_nl#1]
The registration.php has whitespace before the <?php. Therefore magento has trouble to send extra headerinformation and the website will be broken.

**Comment by MrGekko** [comment]
Thanks for your comment! I have no idea how i let that pass. 
But its fixed for all languages!

**Comment by 11mb** [comment]
Thx for the quick fix!

**Comment by MarcioQuimbundo** [comment]
error_reporting(0) will not solve the problem, but it will clean the output error
