### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by markwalravens** [Magento2Translations/language_nl_nl#4]
Can you please correct:
"Subtotal (Excl.Tax)","Subtotaal (incl. BTW)",module,Magento_Tax

Change it to:
"Subtotal (Excl.Tax)","Subtotaal (excl. BTW)",module,Magento_Tax

**Comment by MrGekko** [comment]
I can't directly..  But you can change that on the crowdin project mentioned in the Readme file. The changes will be reflected in this repo within a day.
