### ISSUE TITLE
Update translations?

### ISSUE THREAD

**Issue by peterjaap** [Magento2Translations/language_nl_nl#8]
There are a bunch of new translations in Crowdin that are not in this repository yet.

Could you update them?

Last update in this repo; Auto translate 22/08/2018

Last updates in Crowdin here; https://crowdin.com/project/magento-2/activity_stream

![image](https://user-images.githubusercontent.com/431360/55319578-773e7700-5475-11e9-8708-31ba258b3282.png)

etc etc

**Comment by MrGekko** [comment]
Yes, i will i am working on a beter sollution.

**Comment by MrGekko** [comment]
They have all been updated last week.

**Comment by peterjaap** [comment]
Thanks!
